### ISSUE TITLE
User Credentials

### ISSUE THREAD

**Issue by vignesh-subash** [anmolsaxena10/myHospital#1]
Can you please provide the user credentials pls!!

**Comment by rajesh-h** [comment]
@vignesh-subash Did you get the username and password?

@anmolsaxena10  could you please share login credentials so we can check how it looks?

**Comment by anmolsaxena10** [comment]
usernames:
receptionist
doctor
patient
labattendant

password for all:
qwerty123

**Comment by rajesh-h** [comment]
Thank you very much Anmol
